### PR TITLE
Added LegendWidget

### PR DESCRIPTION
**Pull request by aaranadev**
New LegendWidget is added to all skeletons.

### CODE REVIEW

**Comment by aaranadev** [comment]
This PR is blocked until that https://github.com/CartoDB/carto-react/pull/91 will be merged and a new version will be generated.

**Review by VictorVelarde — COMMENTED** [review]
Changes on sample-app look nice to me (tested with link)... 👍🏻

**Comment by borja-munoz** [comment]
I won't add the LegendWidget to the other two templates. I think it is enough to have an example in the sample-app and this feature is not so core to have it in the skeleton templates.

There is a couple of minor bugs:
- The last interval in the KPI legend is missing the "B" for billions
- The legend title in the Tileset legend says "State analysis" and should say "OSM Buildings"

**Comment by aaranadev** [comment]
> Changes on sample-app look nice to me (tested with link)... 👍🏻

Yes, it's tested with link

**Comment by aaranadev** [comment]
> I won't add the LegendWidget to the other two templates. I think it is enough to have an example in the sample-app and this feature is not so core to have it in the skeleton templates.
> 
> There is a couple of minor bugs:
> 
> * The last interval in the KPI legend is missing the "B" for billions
> * The legend title in the Tileset legend says "State analysis" and should say "OSM Buildings"

Ok, It's the same for me. If you prefer only in sample-app. I'll remove it of the other templates

**Comment by VictorVelarde** [comment]
I'll take this one, to remove legends and review Borja's comments, so to land it asap

**Review by VictorVelarde — APPROVED** [review]
Everything looks nice to me.... 🚀

**Pull request merged**
