### PR TITLE
Improve styleguide in hygen template

### PR DESCRIPTION
**Pull request by aaranadev**

### CODE REVIEW

**Review by alasarr — CHANGES_REQUESTED** [review]
export default in model makes thing harder

**Comment by aaranadev** [comment]
More harder that this?

Screenshot 2021-06-16 at 08 58 04

**Comment by alasarr** [comment]
You're introducing two ways of import.

>More harder that this?

It's not a problem about default, it's a problem of the name of the function

**Comment by aaranadev** [comment]
I think the functionality if you reference the function named `formulateModel` the destructuring is unnecessary.

**Comment by aaranadev** [comment]
The documentation:

> Named exports are useful to export several values. During the import, one will be able to use the same name to refer to the corresponding value.
Concerning the default export, there is only a single default export per module. A default export can be a function, a class, an object or anything else. This value is to be considered as the “main” exported value since it will be the simplest to import.

**Comment by alasarr** [comment]
In general, a model should have more than 1 function. For example StoresModel could have: getStoreById, getAllStores, findNearestStore...

it's odd to do:
```javascript
import getStoreById, {getAllStores, findNearestStore} from ...
```

I know it's allowed and in several libraries (like react for example) is useful because a method is clearly more used than the rest, but not apply for models

**Comment by aaranadev** [comment]
Ok, I understand, I change it

**Comment by aaranadev** [comment]
Done

**Review by alasarr — APPROVED** [review]

**Pull request merged**
