### PR TITLE
Lazy loading for views

### PR DESCRIPTION
**Pull request by aaranadev**

### CODE REVIEW

**Review by alasarr — CHANGES_REQUESTED** [review]
@borja-munoz check a couple of things:
- Do you think it should be in the sample app too? I think not required, but not a strong opinion.
- Check if need to update doc in your side

**Comment by alasarr** [comment]
@aaranadev you need to apply the same changes to skeleton template

**Comment by aaranadev** [comment]
@alasarr the changes are in skeleton template 🤔

**Comment by alasarr** [comment]
The skeleton of cloud native

**Comment by borja-munoz** [comment]
I think it could be helpful to use the lazy loading approach also in the sample app template. In this template we are showing how to work with CARTO for React and this should be the recommended way of working to minimize the file size and improve performance/user experience.

I'll check if I need to update the docs.

**Comment by aaranadev** [comment]
So, it's ok, I prefer merge it and then change cloud native skeleton

**Comment by alasarr** [comment]
>So, it's ok, I prefer merge it and then change cloud native skeleton

Ok, but don't forget please

**Review by alasarr — APPROVED** [review]

**Comment by alasarr** [comment]
Add it to changelog.md

**Pull request merged**
