### PR TITLE
Feature/ch131252/change config by store

### PR DESCRIPTION
**Pull request by albertoarana**

### CODE REVIEW

**Review by alasarr — CHANGES_REQUESTED** [review]
To be honest, I prefer the name `config`. Because:

1) what this module does is to provide config for redux
2) it's useful to extend with other configs


@borja-munoz thoughts?

**Comment by borja-munoz** [comment]
I agree with @alasarr. 

A slice represents/manages a portion of the state tree and the store holds the state tree for the application. It is not related just to configuration.

**Comment by borja-munoz** [comment]
I prefer "store" instead of "config".

From my point of view, a slice represents/manages a portion of the state tree and the store holds the state tree for the whole application. 

It is not related just to configuration. I think it's more broadly related to what variables you are using to manage the state and how you update that state (store) in response to actions.

**Comment by VictorVelarde** [comment]
I'm ok with 'store' as that's the only configuration info we need now, for redux, and it's more detailed than a general 'config', but I don't have a strong opinion.

**Review by VictorVelarde — APPROVED** [review]
👍🏻

**Comment by alasarr** [comment]
It's not a strong opinion, go ahead if you prefer store

**Comment by VictorVelarde** [comment]
Sorry, I was trying to move this on, so I changed to master, merged latest changes there and checked again. But then I have seen that here there are some other changes, beyond the 'config' folder rename, so I'm creating a separated PR for that.

**Comment by VictorVelarde** [comment]
Reverting PR name to original (to avoid misunderstandings with the new PR for the refactor)

**Comment by VictorVelarde** [comment]
This is the new PR, just for the refactor: https://github.com/CartoDB/carto-react-template/pull/201

**Comment by VictorVelarde** [comment]
This is not required anymore, as rename was already done in another PR

**Pull request closed without merging**
