### PR TITLE
Bump carto-react & deck.gl versions + TableWidget example

### PR DESCRIPTION
**Pull request by eamador**
## Upgraded libraries
**carto-react** to `1.2.1-beta.4`
**deck.gl** to `8.7.0-beta.5` 

## TableWidget sample added

`TableWidget` is being added to the `template-sample-app-3` for the _Stores_ view.

https://user-images.githubusercontent.com/9006480/153590631-38ed4cbd-c234-4fe9-a670-65154ea9945a.mov

### CODE REVIEW

**Comment by borja-munoz** [comment]
I think it would be better if we could have the table positioned below the map area, taking all the available width except the space occupied by the sidebar, something similar to Builder layout.

**Comment by VictorVelarde** [comment]
I think we don't want to invest too much time on this @borja-munoz. A bottom one could look better yes, but this one in the panel also serves as a basic table example, which is the point, right? (indeed I did exactly the same with another component, TimeSeries widget)

**Review by Clebal — APPROVED** [review]

**Comment by VictorVelarde** [comment]
I think we can prepare a beta for templates too, as a way to prepare for the upcoming release. I can't think about any issue, but please ping me if you find it

**Comment by borja-munoz** [comment]
> I think we don't want to invest too much time on this @borja-munoz. A bottom one could look better yes, but this one in the panel also serves as a basic table example, which is the point, right? (indeed I did exactly the same with another component, TimeSeries widget)

I think this is important and I see it as a good opportunity to show how we could have a layout where we have a bottom section below the map, maybe with tabs for a time-series widget and a table widget. A table in the sidebar is not really useful and the point of templates is also to show good practices. I can try to implement it myself but I'd need you to review it.

**Review by VictorVelarde — APPROVED** [review]
👍🏻

**Pull request merged**
